/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NflRouteImport } from './routes/nfl'
import { Route as NbaRouteImport } from './routes/nba'
import { Route as MyCalendarRouteImport } from './routes/my-calendar'
import { Route as IplRouteImport } from './routes/ipl'
import { Route as FifaRouteImport } from './routes/fifa'
import { Route as F1RouteImport } from './routes/f1'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CricketTeamsTeamIdRouteImport } from './routes/cricket-teams.$teamId'

const NflRoute = NflRouteImport.update({
  id: '/nfl',
  path: '/nfl',
  getParentRoute: () => rootRouteImport,
} as any)
const NbaRoute = NbaRouteImport.update({
  id: '/nba',
  path: '/nba',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCalendarRoute = MyCalendarRouteImport.update({
  id: '/my-calendar',
  path: '/my-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IplRoute = IplRouteImport.update({
  id: '/ipl',
  path: '/ipl',
  getParentRoute: () => rootRouteImport,
} as any)
const FifaRoute = FifaRouteImport.update({
  id: '/fifa',
  path: '/fifa',
  getParentRoute: () => rootRouteImport,
} as any)
const F1Route = F1RouteImport.update({
  id: '/f1',
  path: '/f1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CricketTeamsTeamIdRoute = CricketTeamsTeamIdRouteImport.update({
  id: '/cricket-teams/$teamId',
  path: '/cricket-teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/f1': typeof F1Route
  '/fifa': typeof FifaRoute
  '/ipl': typeof IplRoute
  '/my-calendar': typeof MyCalendarRoute
  '/nba': typeof NbaRoute
  '/nfl': typeof NflRoute
  '/cricket-teams/$teamId': typeof CricketTeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/f1': typeof F1Route
  '/fifa': typeof FifaRoute
  '/ipl': typeof IplRoute
  '/my-calendar': typeof MyCalendarRoute
  '/nba': typeof NbaRoute
  '/nfl': typeof NflRoute
  '/cricket-teams/$teamId': typeof CricketTeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/f1': typeof F1Route
  '/fifa': typeof FifaRoute
  '/ipl': typeof IplRoute
  '/my-calendar': typeof MyCalendarRoute
  '/nba': typeof NbaRoute
  '/nfl': typeof NflRoute
  '/cricket-teams/$teamId': typeof CricketTeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/f1'
    | '/fifa'
    | '/ipl'
    | '/my-calendar'
    | '/nba'
    | '/nfl'
    | '/cricket-teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/f1'
    | '/fifa'
    | '/ipl'
    | '/my-calendar'
    | '/nba'
    | '/nfl'
    | '/cricket-teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/f1'
    | '/fifa'
    | '/ipl'
    | '/my-calendar'
    | '/nba'
    | '/nfl'
    | '/cricket-teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  F1Route: typeof F1Route
  FifaRoute: typeof FifaRoute
  IplRoute: typeof IplRoute
  MyCalendarRoute: typeof MyCalendarRoute
  NbaRoute: typeof NbaRoute
  NflRoute: typeof NflRoute
  CricketTeamsTeamIdRoute: typeof CricketTeamsTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nfl': {
      id: '/nfl'
      path: '/nfl'
      fullPath: '/nfl'
      preLoaderRoute: typeof NflRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nba': {
      id: '/nba'
      path: '/nba'
      fullPath: '/nba'
      preLoaderRoute: typeof NbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-calendar': {
      id: '/my-calendar'
      path: '/my-calendar'
      fullPath: '/my-calendar'
      preLoaderRoute: typeof MyCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipl': {
      id: '/ipl'
      path: '/ipl'
      fullPath: '/ipl'
      preLoaderRoute: typeof IplRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fifa': {
      id: '/fifa'
      path: '/fifa'
      fullPath: '/fifa'
      preLoaderRoute: typeof FifaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f1': {
      id: '/f1'
      path: '/f1'
      fullPath: '/f1'
      preLoaderRoute: typeof F1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricket-teams/$teamId': {
      id: '/cricket-teams/$teamId'
      path: '/cricket-teams/$teamId'
      fullPath: '/cricket-teams/$teamId'
      preLoaderRoute: typeof CricketTeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  F1Route: F1Route,
  FifaRoute: FifaRoute,
  IplRoute: IplRoute,
  MyCalendarRoute: MyCalendarRoute,
  NbaRoute: NbaRoute,
  NflRoute: NflRoute,
  CricketTeamsTeamIdRoute: CricketTeamsTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
