/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NbaIndexRouteImport } from './routes/nba/index'
import { Route as F1IndexRouteImport } from './routes/f1/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NbaIndexRoute = NbaIndexRouteImport.update({
  id: '/nba/',
  path: '/nba/',
  getParentRoute: () => rootRouteImport,
} as any)
const F1IndexRoute = F1IndexRouteImport.update({
  id: '/f1/',
  path: '/f1/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/f1/': typeof F1IndexRoute
  '/nba/': typeof NbaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/f1': typeof F1IndexRoute
  '/nba': typeof NbaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/f1/': typeof F1IndexRoute
  '/nba/': typeof NbaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/f1/' | '/nba/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/f1' | '/nba'
  id: '__root__' | '/' | '/f1/' | '/nba/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  F1IndexRoute: typeof F1IndexRoute
  NbaIndexRoute: typeof NbaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nba/': {
      id: '/nba/'
      path: '/nba'
      fullPath: '/nba/'
      preLoaderRoute: typeof NbaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f1/': {
      id: '/f1/'
      path: '/f1'
      fullPath: '/f1/'
      preLoaderRoute: typeof F1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  F1IndexRoute: F1IndexRoute,
  NbaIndexRoute: NbaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
